name: Tessera Maven Build

on:
  push:
    branches:
      - psv_merge
  pull_request:
    branches:
      - new-psv
env: 
  MAVEN_REPO_CACHE_KEY: ${{ github.run_id }}-maven-${{ github.run_number }}-${{ github.run_number }}-${{ github.sha }}
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
              java-version: 11
        - run: |
           mvn install -Dsilent=true -DskipTests=true -Dmaven.javadoc.skip=true -Dchecksyle.skip=true -Dspotbugs.skip=true -Djacoco.skip=true -B
           mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -B
           mvn dependency:go-offline -B
           mvn dependency:resolve-plugins -B

        - uses: actions/cache@v1
          with:
            path: ~/.m2/repository
            key: ${{env.MAVEN_REPO_CACHE_KEY}}
            restore-keys: |
              ${{env.MAVEN_REPO_CACHE_KEY}}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{env.MAVEN_REPO_CACHE_KEY}}
          restore-keys: |
            ${{env.MAVEN_REPO_CACHE_KEY}}
      - run:  mvn package -pl \!tests/acceptance-test  
      - uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: unittests
          fail_ci_if_error: true
      - run: |
          mkdir -p /home/runner/work/tessera/tessera/surefire-reports
          cp -u **/target/surefire-reports/* /home/runner/work/tessera/tessera/surefire-reports/
        if: failure()
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: junit-reports
          path: /home/runner/work/tessera/tessera/surefire-reports
            
  itest:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 11
        - uses: actions/cache@v1
          with:
            path: ~/.m2/repository
            key: ${{env.MAVEN_REPO_CACHE_KEY}}
            restore-keys: |
              ${{env.MAVEN_REPO_CACHE_KEY}}
        - run: mvn verify -pl tests/acceptance-test
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: itest-failsafe-reports
            path: /home/runner/work/tessera/tessera/tests/acceptance-test/target/failsafe-reports

  vaultTests:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 11
        - uses: actions/cache@v1
          with:
            path: ~/.m2/repository
            key: ${{env.MAVEN_REPO_CACHE_KEY}}
            restore-keys: |
             ${{env.MAVEN_REPO_CACHE_KEY}}
        - run: |
            wget https://releases.hashicorp.com/vault/1.2.2/vault_1.2.2_linux_amd64.zip -O /tmp/vault_1.2.2_linux_amd64.zip
            mkdir -p vault/bin && pushd $_
            unzip /tmp/vault_1.2.2_linux_amd64.zip
            export PATH=$PATH:$PWD && popd
            mvn verify -pl tests/acceptance-test -P vault-acceptance-tests

  atest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: QuorumEngineering/quorum
          path: quorum
          token: 889164eb89db2348e0d26aed4c1e4a47a1a5c98a
          ref: feature/quorum-1.9.7-withPE
      - uses: actions/checkout@v2
        with:
          repository: QuorumEngineering/quorum-acceptance-tests
          path: quorum-acceptance-tests
          token: 889164eb89db2348e0d26aed4c1e4a47a1a5c98a
          ref: feature/quorum-1.9.7-withPE
      - uses: actions/checkout@v2
        with:
          repository: QuorumEngineering/quorum-examples
          path: quorum-examples
          token: 889164eb89db2348e0d26aed4c1e4a47a1a5c98a
          ref: geth-1.9.7
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{env.MAVEN_REPO_CACHE_KEY}}
          restore-keys: |
            ${{env.MAVEN_REPO_CACHE_KEY}}
      - run: |
          export TESSERA_JAR=`ls ~/.m2/repository/com/jpmorgan/quorum/tessera-app/*/tessera-app-*-app.jar`

          cd /home/runner/work/tessera/tessera/quorum
          make all
          export PATH=$PATH:$(pwd)/build/bin
          cd /home/runner/work/tessera/tessera/
          geth version
          echo "Installed geth"
          
          echo "Install solc"
          curl -L https://github.com/ethereum/solidity/releases/download/v0.5.4/solc-static-linux -o solc
          sudo mv solc /usr/local/bin/
          sudo chmod 755 /usr/local/bin/solc
          solc --version
          echo "Installed solc"
          echo "Install gauge"
          curl -L https://github.com/getgauge/gauge/releases/download/v1.0.7/gauge-1.0.7-linux.x86_64.zip -o gauge.zip
          sudo unzip -o gauge.zip -d /usr/local/bin

          cd /home/runner/work/tessera/tessera/quorum-acceptance-tests
          gauge install
          cd /home/runner/work/tessera/tessera
          echo "Installed gauge"
          echo "Start $TESSERA_JAR for 7 nodes"
          cd /home/runner/work/tessera/tessera/quorum-examples/examples/7nodes
          ./tessera-init.sh
          ./init.sh istanbul
          ./start.sh istanbul tessera
          cd /home/runner/work/tessera/tessera
          echo "Started $TESSERA_JAR for 7 nodes"
          echo "Run quorum-acceptance-tests"
          cd /home/runner/work/tessera/tessera/quorum-acceptance-tests
          cp config/application-local.7nodes.yml config/application-local.yml
          mvn test
          echo "Complete quorum-acceptance-tests"
        env:
          MAVEN_OPTS: -Xms1024m -Xmx2048m

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
            name: gauge-report
            path: /home/runner/work/tessera/tessera/quorum-acceptance-tests/src/site/resources/reports/html-report/
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
            name: quorum-examples-logs
            path: /home/runner/work/tessera/tessera/quorum-examples/examples/7nodes/qdata/logs

